name: Environment Setup
inputs:
  KUBECONFIG_DATA:
    required: true
env:
  KUBECONFIG: /tmp/github-ci.kubeconfig
runs:
  using: composite
  steps:
    - run: "echo -n '${{ inputs.KUBECONFIG_DATA }}' > \"${KUBECONFIG}\""
      shell: bash
    - run: |
        NAMESPACE=$(yq '.contexts.0.context.namespace' ${KUBECONFIG})
        if [ "${NAMESPACE}" != "vshn-api-gateway-gravitee-test" ]; then
          echo "::error::kubeconfig context namespace must be 'vshn-api-gateway-gravitee-test', got '${NAMESPACE}'"
          exit 1
        fi
        echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV
      shell: bash
