gravitee:
  mongodb:
    enabled: false
  mongo:
    dbhost: gravitee-mongodb
    rsEnabled: false
  elasticsearch:
    enabled: false
  es:
    enabled: false
  api:
    analytics:
      type: none
    ingress:
      management:
        enabled: false
      portal:
        enabled: false
  installation:
    api:
      url: http://localhost:8083
  gateway:
    reporters:
      elasticsearch:
        enabled: false
    ingress:
      enabled: false
  ui:
    baseURL: http://localhost:8083/management
    ingress:
      enabled: false
  portal:
    baseURL: http://localhost:8083/portal
    ingress:
      enabled: false

httpbun:
  enabled: true

initJob:
  enabled: true # requires httpbun.enabled=true (creates /httpbun API)

env: {}
