gravitee:
  mongodb:
    enabled: false
  mongo:
    dbhost: gravitee-mongodb
    rsEnabled: false
  elasticsearch:
    enabled: false
  es:
    enabled: false
  api:
    analytics:
      type: none
    deployment:
      securityContext:
        runAsUser: 1003120000
        runAsGroup: 0
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
    ingress:
      management:
        enabled: false
      portal:
        enabled: false
  installation:
    api:
      url: http://localhost:8083
  gateway:
    reporters:
      elasticsearch:
        enabled: false
    deployment:
      securityContext:
        runAsUser: 1003120000
        runAsGroup: 0
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
    ingress:
      enabled: false
  ui:
    baseURL: http://localhost:8083/management
    deployment:
      securityContext:
        runAsUser: 1003120000
        runAsGroup: 0
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
    ingress:
      enabled: false
  portal:
    baseURL: http://localhost:8083/portal
    deployment:
      securityContext:
        runAsUser: 1003120000
        runAsGroup: 0
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
    ingress:
      enabled: false

httpbun:
  enabled: true

initJob:
  enabled: true # requires httpbun.enabled=true (creates /httpbun API)

env: {}
