name: test-stop
"on":
  workflow_dispatch: {}

env:
  KUBECONFIG: /tmp/github-ci.kubeconfig

jobs:
  stop:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_TEST }}

      - name: Helm Chart stop
        run: |
          cp "${KUBECONFIG}" ".github-ci.kubeconfig"
          docker run -v "${PWD}:/data" -w /data ghcr.io/appuio/helm-v4:latest /bin/bash -c "cp .github-ci.kubeconfig /tmp/github-ci.kubeconfig; chmod 400 /tmp/github-ci.kubeconfig; /bin/helm uninstall 'gravitee-test' --namespace '${NAMESPACE}' --kubeconfig /tmp/github-ci.kubeconfig"
