env:
  KUBECONFIG: /tmp/github-ci.kubeconfig
  REGISTRY: registry.cloudscale-lpg-2.appuio.cloud
  TEST_DOMAIN: apps.cloudscale-lpg-2.appuio.cloud
jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          KUBECONFIG_DATA: "${{ secrets.KUBECONFIG_TEST }}"
      - env:
          NEWLINE: |2+

          SECRETS_JSON: "${{ toJson(secrets) }}"
          VARS_JSON: "${{ toJson(vars) }}"

          APPFLOW_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          APPFLOW_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          APPFLOW_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        name: Helm Chart preview
        run: |
          ENVV=$(jq -n --arg p 'APPFLOW_' 'env | with_entries(select(.key | startswith($p)))')
          VARS=$(jq -n --arg p 'APPFLOW_' 'env.VARS_JSON | fromjson? // {} |  with_entries(select(.key | startswith($p)))')
          SECRETS=$(jq -n --arg p 'APPFLOW_' 'env.SECRETS_JSON | fromjson? // {} | with_entries(select(.key | startswith($p)))')
  
          jq -n --arg p 'APPFLOW_' --argjson e "$ENVV" --argjson v "$VARS" --argjson s "$SECRETS" \
          '{env: ($e + $v + $s + ($e + $v + $s | with_entries(.key |= ltrimstr($p))))}' > "${PWD}/env.yaml"

          
          jq '.env | keys' "${PWD}/env.yaml"
          
          cp "${KUBECONFIG}" ".github-ci.kubeconfig"
          sudo chmod -R o+w $(printf '%s' "$PWD")
          docker run -v "${PWD}:/data" -w /data ghcr.io/appuio/helm-v4:latest /bin/bash -c "cp .github-ci.kubeconfig /tmp/github-ci.kubeconfig; chmod 400 /tmp/github-ci.kubeconfig; /bin/helm dependency update '/data'; HELM_DIFF_USE_UPGRADE_DRY_RUN=true /bin/helm diff upgrade 'test' '/data' --namespace '${NAMESPACE}' --values '/data/values.yaml' --values '/data/env.yaml' --kubeconfig /tmp/github-ci.kubeconfig --allow-unreleased"
      - env:
          NEWLINE: |2+

          SECRETS_JSON: "${{ toJson(secrets) }}"
          VARS_JSON: "${{ toJson(vars) }}"
          APPFLOW_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          APPFLOW_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          APPFLOW_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        name: Helm Chart deploy
        run: |
          ENVV=$(jq -n --arg p 'APPFLOW_' 'env | with_entries(select(.key | startswith($p)))')
          VARS=$(jq -n --arg p 'APPFLOW_' 'env.VARS_JSON | fromjson? // {} |  with_entries(select(.key | startswith($p)))')
          SECRETS=$(jq -n --arg p 'APPFLOW_' 'env.SECRETS_JSON | fromjson? // {} | with_entries(select(.key | startswith($p)))')
  
          jq -n --arg p 'APPFLOW_' --argjson e "$ENVV" --argjson v "$VARS" --argjson s "$SECRETS" \
          '{env: ($e + $v + $s + ($e + $v + $s | with_entries(.key |= ltrimstr($p))))}' > "${PWD}/env.yaml"
        
          cp "${KUBECONFIG}" ".github-ci.kubeconfig"
          sudo chmod -R o+w $(printf '%s' "$PWD")
          docker run -v "${PWD}:/data" -w /data ghcr.io/appuio/helm-v4:latest /bin/bash -c "cp .github-ci.kubeconfig /tmp/github-ci.kubeconfig; chmod 400 /tmp/github-ci.kubeconfig; /bin/helm dependency update '/data'; HELM_DIFF_USE_UPGRADE_DRY_RUN=true /bin/helm diff upgrade 'test' '/data' --namespace '${NAMESPACE}' --values '/data/values.yaml' --values '/data/env.yaml' --kubeconfig /tmp/github-ci.kubeconfig --allow-unreleased"
name: Build and deploy to test
"on":
  push:
    branches:
      - '**'
  workflow_dispatch: {}